repos:
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        language_version: python3.9
        # override until resolved: https://github.com/ambv/black/issues/402
        files: \.pyi?$
        types: []

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: ["--config", ".flake8" ]
        language_version: python3.9
        additional_dependencies:
        - flake8-bugbear
        - flake8-deprecated
        - flake8-comprehensions
        - flake8-isort
        - flake8-quotes
        - flake8-mutable
        - flake8-todo
        - flake8-builtins
#
#  - repo: https://github.com/pre-commit/mirrors-isort
#    rev: v4.3.21
#    hooks:
#      - id: isort
#        additional_dependencies: [toml]
#        language_version: python3.9
#


#  - repo: git://github.com/doublify/pre-commit-clang-format
#    rev: master
#    hooks:
#    - id: clang-format
#      args: [ "-style=file" ]

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
    -   id: pyupgrade
        args: ['--py36-plus']

  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
    -   id: codespell
        name: codespell
        description: Checks for common misspellings in text files.
        entry: codespell
        language: python
        types: [text]

#  - repo: https://github.com/pre-commit/mirrors-clang-format
#    rev: 'v13.0.0'
#    hooks:
#    -   id: clang-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
#      - id: debug-statements
